# This workflow will do a clean install of node dependencies and run a linter across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Bun.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Bun.js
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install --production --frozen-lockfile
      - run: bun run lint
      - run: bun run test-ci
